version: "3.7"

services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    volumes:
      - postgres124-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      main:
        aliases:
          - postgres

volumes:
  postgres124-data: {}

networks:
  main: